### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by Larsouille25** [zom-lang/zom#14]
*It's the tracking issue of the [`RFC-0007`](https://github.com/zom-lang/evolution/pull/7)*

### Todo
- [x] ~~Multi line comments with `/*` to begin and `*/` to finish~~
- [x] single line comments with `//`

**Comment by Larsouille25** [comment]
Comments are now supported.

**Comment by Larsouille25** [comment]
I'm not happy with comments, now, for simplicity, comments starts with `#` (for simplicity) and end with `\n`.

- [ ] But I don't like that, instead, I prefer comments that start with `(*` and end with `*)`. 
- [ ] After implementing comments like this, you will have to write the doc for the comments with the number 14 (because that is the problem number)

**Comment by Larsouille25** [comment]
It's done! 636eecb1a937ebf3f6ae614c7f0459a35240c460

**Comment by Larsouille25** [comment]
Add single line comments with `#`.

**Comment by Larsouille25** [comment]
Done !

**Comment by Larsouille25** [comment]
Finally, reopen the issue to have slashes comment, it will be definitive.

**Comment by Larsouille25** [comment]
It's done multi line comments will not be added it's useless, and single line comments are implemented.
