### ISSUE TITLE
Replace anyhow error with custom errors

### ISSUE THREAD

**Issue by Larsouille25** [zom-lang/zom#30]
In the binary `zom`, replace all anyhow errors with custom made errors in `zom_common`.

- [x] implement #4 ~~with a "reverse lexer"~~
- [x] Create the `ZomError` struct,
- [x] implement the `Error` trait.
- [x] Make parameter `location` optional.
- [x] Replace actual struct like `IllegalCharError` with a function (or macro) that create a new ZomError.
- [x] Add `EOF` token
- [x] In crate `zom`, replace anyhow errors with ZomError.
- [x] Remove `anyhow = { version = "1.0.71", default-features = false }`, in `zom/Cargo.toml`
- [x] Create a panic hook to create and print the internal error.

To facilitate debugging of the code and why there is errors,
- [x] Transform the return type of the lexer to a `Vec<Result<..,..>>` instead of `Result<vec<..>,..>`
- [x] The same for the parser: from `Result<(Vec<ASTNode>, Vec<Token>), ZomError>` to `Result<Vec<ASTNode>, Vec<ZomError>>`  -> https://github.com/zom-lang/zom/issues/30#issuecomment-1669418927
- [x] ~~And try for the compiler and the codegen too if it's possible~~ -> #44 

In another branch,
- [x] ~~try to replace PartParsingResult with Result.~~ -> https://github.com/zom-lang/zom/issues/30#issuecomment-1669418927

**Comment by Larsouille25** [comment]
Instead of having custom struct that implement the `ZomError` trait; Transform `ZomError` to a struct.
Actual struct like `IllegalCharError` will be replaced by a function that create a new `ZomError` with the right parameters

**Comment by Larsouille25** [comment]
It's said in e769064 that the parser can partialy return multiple errors, it's normal and it can only return multiple errors when an unexpected token is in the `while let` loop of the function parse() because after the smaller function need to return something and for the moment I don't know how to do it. 

But it's planed to when an error occur while parsing a function definition or declaration, to skip tokens related to this AST and push the error into the list and continue parse other function definition / declaration etc ...
