### ISSUE TITLE
Tracking Issue for primitives

### ISSUE THREAD

**Issue by thi8v** [zom-lang/zom#51]
This is a tracking issue for the RFC "primitives" (zom-lang/rfcs#0003).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or 
open design questions. A tracking issue is however *not* meant for large scale
discussion, questions, or bug reports about a feature. Instead, open a dedicated
issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC
  - [ ] Literals ->
    - [x] Int
    - [ ] Float
    - [x] int: binary, octal, hexadecimal literals -> not yet, create another issue for this.
    - [x] `char`
    - [x] `str`
    - [ ] escape sequences
      - [ ] `\xNN`
      - [x] `\n`
      - [x] `\r`
      - [x] `\t`
      - [x] `\\`
      - [x] `\0`
      - [x] `\'`
      - [x] `\"`
  - [x] `usize` and `isize`
  - [x] `true` and `false` keywords
  - [x] boolean expression
  - [x] `undefined` keyword
  - [x] an `undefined` expression
- [x] Adjust documentation. -> #22 

### Unresolved Questions

N/A

### Implementation history

- 63f4ec4fb613946e241d421ef40ce3cc40b6d730
- e97bfea0486db1b11e4df00618086227defff738
- 84d383d9289be7ccc45639fc7c3af135ca82ce33
